### ISSUE TITLE
Disabling "titlecase" for multilingual

### ISSUE THREAD

**Issue by uaqben** [octopress/multilingual#18]
I suggest to disable the `titlecase` Octopress Filter either by default, or at least when using `octopress-multilingual`.

In other languages, such as French or Spanish, it is incorrect to "Capitalize All The Words" of a title for example.

I can undertand that this filter provides convenience, but thenagain Capitalizing one's titles can easily be done directly in one's source files.

Maybe `titlecase` could be turned on/off via a `switch` in the `_config.yml`?

FYI, I've tried editing my `Octopress` gem, setting `'titlecase' => false` in `lib/octopress/page.rb`

Didn't work.. my titles are still being capitalized :(

I welcome any info/recommendations on how to turn it off :)

**Comment by imathis** [comment]
You can disable titlecase by setting `titlecase: false` in your `_config.yml`.

**Comment by uaqben** [comment]
@imathis, I had tried setting that flag in `_config.yml`, however, it didn't work, and so I thought it wasn't implemented...

my `_config.yml`:

```
[...]
markdown: kramdown
titlecase: false

gems:
  - octopress-multilingual
  - octopress-linkblog
```

I also checked my CSS files, in case it was capitalizing titles, but it isn't.

When I view a rendered page, for example, I get:

```
    <section id="About" class="container content-section text-center">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2">

          <header class="post-header">
            <h1>About</h1>
          </header>
```

yet the `about.en.md` page is:

```
---
layout: page
lang: en
title: about
permalink: /en/about/
```

Any idea as to how I can solve/troubleshoot this `titlecase` issue?
