### ISSUE TITLE
Multilingual pages

### ISSUE THREAD

**Issue by drallgood** [octopress/multilingual#2]
Most sites will not only have posts in multiple languages but also pages. 

Aside from the two use-cases we already covered for posts (i.e. cross-posts), pages can also be not language specific at all, e.g. to allow your users to choose their language.

**Comment by imathis** [comment]
@drallgood I assume that for language specific pages, users will place them under the language directory. For site-wide pages, they would just leave them outside of that directory. Currently Octopress's `new` command supports the `--lang` option for both pages and posts. Since people don't typically work with the `site.pages` array like they do for posts, is there some feature that I could add for pages beyond this?

**Comment by imathis** [comment]
I've just added a `{% post_lang %}` liquid block tag that makes handling the `site.posts` loop even easier. Check out the [updated docs](https://github.com/octopress/multilingual#post-indexes-and-rss-feeds) and let me know what you think.

**Comment by drallgood** [comment]
I have to give it a try, but so far everything looks like it should work just fine :)

I'll keep you posted.

**Comment by imathis** [comment]
I've just released an update, 0.0.3, and I've changed the `post_lang` tag `set_lang` and it also temporarily sets the `site.lang` setting. I've updated the docs on that considerably, so take a look again if you like.

**Comment by drallgood** [comment]
Looks good.

One question, though. Shouldn't it be `{endset_lang}` instead of `{endpost_lang}`?

**Comment by imathis** [comment]
Thanks, that was a typo. Fixed!

**Comment by imathis** [comment]
Aside from dictionary translation (which I'm still considering) are there any multilingual page features you can suggest? I'm not sure if this ticket has a direction.

**Comment by drallgood** [comment]
Nope. 
I think, with what you've already implemented and the dictionary translation we've covered everything I can think of. 

This ticket really has no direction :smile:

**Comment by imathis** [comment]
Awesome, thanks for all your help!
