### ISSUE TITLE
Language indicator for crossposts

### ISSUE THREAD

**Issue by drallgood** [octopress/multilingual#7]
I'm wondering whether it makes sense to also provide a way to add an indicator (e.g. a flag) to cross-posts. Like I'm doing it on [my blog](http://brendamour.net/de/),

You can already do this in your template, so I'm not so sure this is even worth considering. 
I've solved this using a custom liquid filter:

``` liquid
{{ post | language_flag }} => <img src='/images/en.png' alt='Crosspost' class='flag'/>
{{ post | language_text }} => (en)
```

What do you guys think?

**Comment by imathis** [comment]
I think there's a strong case for not using flags to represent languages, read [Why flags do not represent languages](http://flagsarenotlanguages.com/blog/why-flags-do-not-represent-language/). But it's a common practice and blog authors will probably ask for it. I think for now I'm going to leave this to site authors to solve.

**Comment by drallgood** [comment]
Yeah. It's easy enough to implement yourself anyway. 

Thanks.
